language: node_js

node_js:
  - 10.14.2

before_install: git fetch --depth=1000

# npm i --registry=https://registry.npm.taobao.org
install:
  - npm i

cache: npm

script:
  - npm run lint
  - npm run test:unit

before_deploy:
  - echo "deploying..."

# @see https://docs.travis-ci.com/user/deployment/pages/
deploy:
  -
    provider: pages
    local-dir: dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    skip-cleanup: true
    keep-history: true
    on:
      tags: true

notifications:
  email:
    recipients:
      - bqliu@iflytek.com

after_deploy:
  - echo "deployed."
